version: "3.4"

networks:
  libraryapi:

services:
  libraryvue.server:
    image: ${DOCKER_REGISTRY-}libraryvueserver
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
    container_name: libraryvue.api
    networks:
      - libraryapi
    volumes:
      - ~/.aspnet/https:/https:ro
      - ./.containers/logs:/log
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx

  libraryvue.database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: libraryvue.database
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Passw0rd!
    ports:
      - 1433:1433
    networks:
      - libraryapi
