@LibraryVue.Server_HostAddress = https://localhost:7021

###
GET {{LibraryVue.Server_HostAddress}}/api/Book/Getall
Accept: application/json

###
POST {{LibraryVue.Server_HostAddress}}/api/Authenticate/login
Accept: application/json
